name: Fuzz
on:
    workflow_dispatch: 
    schedule:
        - cron: "0 0 * * 0" 
jobs:
  libFuzzer:
    strategy:
      matrix:
        target:
            - handshake::tests::fuzz_acceptor_respond
            - handshake::tests::fuzz_initiator_finalize
            - keys::tests::fuzz_private_key_from_str
            - keys::tests::fuzz_public_key_from_slice
            - keys::tests::fuzz_public_key_from_str
            - tests::fuzz_transport
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-C target-feature=+aes,+ssse3"
    steps:
      - uses: actions/checkout@v4
      - uses: RustCrypto/actions/cargo-cache@master
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - run: cargo +stable install cargo-bolero -f
      - run: cargo +nightly bolero test ${{ matrix.target }} -T 5m