[package]
name = "yrgourd"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bytes = "1.5.0"
curve25519-dalek = { version = "4.1.1", features = ["rand_core"] }
futures = "0.3.29"
hex = "0.4.3"
lockstitch = { git = "https://github.com/codahale/lockstitch" }
pin-project-lite = "0.2.13"
rand_core = "0.6.4"
thiserror = "1.0.50"
tokio = { version = "1.34.0", default-features = false, features = ["bytes", "io-util"] }
tokio-util = { version = "0.7.10", default-features = false, features = ["codec"] }

[dev-dependencies]
bolero = "0.10.0"
rand_chacha = "0.3.1"
tokio = { version = "1.34.0", default-features = false, features = ["full"] }

[lints]
workspace = true
