[package]
name = "yrgourd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curve25519-dalek = { version = "4.1.1", features = ["rand_core"] }
lockstitch = "0.17.0"
rand = { version = "0.8.5", features = ["min_const_gen"] }
rand_chacha = "0.3.1"
